branches:
  only:
    - master
language: node_js
node_js:
  - '10'
  - '12'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$(yarn global bin):$PATH"
cache: yarn
install:
  - yarn --frozen-lockfile
before_script:
  - export FAKE_HOSTNAME=travis-box
script: yarn test-coverage

stages:
  - name: test
  - name: release
    if: branch = master AND type = push
jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
